version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
  

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
